# Generated by Django 2.2.6 on 2019-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bio', models.CharField(max_length=500)),
                ('likes_design', models.BooleanField()),
            ],
        ),
    ]
