# Generated by Django 2.2.6 on 2019-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20191005_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes_design',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.jps', upload_to='profile_pics'),
        ),
    ]
